name: "CI"
on:
  pull_request_target:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Setup project
        run: |
          npm install
          npm run package
      - name: Check lint
        run: |
          npm run lint
